import { useEffect, useState } from 'react';
import { Link, NavLink, Outlet, useLocation } from 'react-router-dom';
import { company,navItems } from '../data/site';
const seo:Record<string,[string,string]>={
 '/':['OMICS | 전통 발효를 더 쉽고 정밀하게','스마트 발효기기와 전통 발효 키트로 새로운 발효 경험을 준비하는 OMICS입니다.'],
 '/products':['제품 | OMICS','OMICS 스마트 발효기기, 전통 발효 키트와 구독 서비스를 확인하세요.'], '/kits':['발효 키트·구독 | OMICS','전통 발효를 시작하고 이어가기 위한 키트와 구독 서비스입니다.'],
 '/recipes':['레시피·발효 가이드 | OMICS','된장, 간장, 고추장 등 발효 과정과 준비 방법을 살펴보세요.'], '/technology':['스마트 발효 기술 | OMICS','발효 환경 관리와 기록을 돕기 위해 개발 중인 OMICS 기술을 소개합니다.'],
 '/brand':['브랜드 스토리 | OMICS','전통 발효문화와 현대 기술을 연결하는 OMICS의 생각입니다.'], '/stores':['공식 판매처 | OMICS','OMICS의 확인된 공식 판매 채널 현황을 안내합니다.'], '/b2b':['B2B·OEM 문의 | OMICS','식품, 유통, 원재료, 연구 및 해외 협력 문의 안내입니다.']};
export function Layout(){const [open,setOpen]=useState(false);const loc=useLocation();useEffect(()=>{const base=loc.pathname.startsWith('/products/')?['제품 상세 | OMICS','OMICS 제품의 특징과 출시 정보를 확인하세요.']:loc.pathname.startsWith('/recipes/')?['발효 가이드 | OMICS','OMICS 발효 가이드의 준비 과정과 주의사항입니다.']:seo[loc.pathname]??['OMICS','전통 발효를 오늘의 생활에 연결합니다.'];document.title=base[0];let meta=document.querySelector<HTMLMetaElement>('meta[name="description"]');if(!meta){meta=document.createElement('meta');meta.name='description';document.head.append(meta)}meta.content=base[1];},[loc.pathname]); return <><a className="skip" href="#main">본문 바로가기</a><header className="header"><div className="shell nav"><Link className="logo" to="/" aria-label="OMICS 홈">OMICS<span>SMART FERMENTATION</span></Link><button className="menu" aria-expanded={open} aria-controls="main-nav" onClick={()=>setOpen(!open)}><span aria-hidden>☰</span> 메뉴</button><nav id="main-nav" className={open?'open':''} aria-label="주요 메뉴">{navItems.map(n=><NavLink key={n.to} to={n.to} onClick={()=>setOpen(false)} className={({isActive})=>isActive?'active':''}>{n.label}</NavLink>)}</nav></div></header><main id="main" key={loc.pathname}><Outlet/></main><Footer/></>}
function Footer(){return <footer><div className="shell footer-grid"><div><div className="logo light">OMICS<span>SMART FERMENTATION</span></div><p>전통 발효를 오늘의 생활에 맞게 연결합니다.</p></div><div><strong>회사 정보</strong><p>회사명 {company.name} · 대표자 {company.representative}<br/>사업자등록번호 {company.businessNumber}<br/>통신판매업 신고번호 {company.mailOrderNumber}<br/>주소 {company.address}</p></div><div><strong>문의</strong><p><a href={`tel:${company.phone}`}>{company.phone}</a><br/><a href={`mailto:${company.email}`}>{company.email}</a></p><div className="footer-links"><Link to="/privacy">개인정보처리방침</Link><Link to="/terms">이용약관</Link><Link to="/stores">구매안전 안내 · 공식 판매처</Link></div></div></div><div className="shell copyright">© {new Date().getFullYear()} OMICS. All rights reserved.</div></footer>}
