import type { ReactNode } from 'react';
import { Link } from 'react-router-dom';
import { categoryLabels } from '../data/products';
import type { Product } from '../types';
import { trackEvent } from '../lib/analytics';
export function PageHero({eyebrow,title,children,actions}:{eyebrow:string;title:string;children:ReactNode;actions?:ReactNode}){return <section className="page-hero"><div className="shell"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p className="lead">{children}</p>{actions&&<div className="actions">{actions}</div>}</div></section>}
export function Section({eyebrow,title,intro,children,id,className=''}:{eyebrow?:string;title:string;intro?:string;children:ReactNode;id?:string;className?:string}){return <section id={id} className={`section ${className}`}><div className="shell">{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{intro&&<p className="section-intro">{intro}</p>}{children}</div></section>}
export function Placeholder({label,ratio='4:3'}:{label:string;ratio?:string}){return <div className="placeholder" style={{aspectRatio:ratio}} role="img" aria-label={`${label} 이미지 준비 중`}><span>IMAGE PLACEHOLDER</span><strong>{label}</strong><small>권장 비율 {ratio}</small></div>}
export function ProductCard({product}: {product:Product}){return <article className="card product-card"><Placeholder label={product.name}/><div className="card-body"><div className="meta"><span>{categoryLabels[product.category]}</span><span className="status">출시 예정</span></div><h3>{product.name}</h3><p>{product.summary}</p><strong className="price">{product.price?`${product.price.toLocaleString()}원`:'가격 확인 후 입력'}</strong><div className="card-actions"><Link className="button secondary" to={`/products/${product.slug}`} onClick={()=>trackEvent('view_product',{product:product.id})}>상세보기</Link><Link className="text-link" to="/stores">판매처 보기 →</Link></div></div></article>}
export function StoreLink({href,label,channel}:{href:string;label:string;channel:string}){return <a className="button" href={href} target="_blank" rel="noopener noreferrer" onClick={()=>trackEvent(channel==='coupang'?'click_coupang':channel==='naver'?'click_smartstore':'click_store',{channel})}>{label}<span aria-hidden> ↗</span></a>}
